// This file was auto-generated by prisma-generator-typescript-interfaces

export interface User {
  id: string;
  email: string;
  name: string | null;
  image: string | null;
  forms?: Form[];
}

export interface Form {
  id: string;
  userId: string;
  user?: User;
  name: string;
  description: string | null;
  screenshot: string | null;
  questions?: Question[];
  response?: Response[];
  isPublic: boolean;
  allowResponses: boolean;
  theme: string | null;
}

export interface Question {
  id: string;
  formId: string;
  form?: Form;
  type: string;
  text: string;
  required: boolean;
}

export interface Response {
  id: string;
  formId: string;
  form?: Form;
  answers: JsonValue;
  createdAt: Date;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
